language: php

php:
  - 5.5
  - 5.4

before_install:
    - composer self-update
    - cp app/config/parameters.yml.dist app/config/parameters.yml
    - psql -c "CREATE USER forex WITH PASSWORD 'forex';" -U postgres
    - psql -c 'CREATE DATABASE forex;' -U postgres
    - psql -c 'GRANT ALL PRIVILEGES ON DATABASE forex to forex;' -U postgres

before_script:
    - composer install
    - app/console doctrine:migrations:migrate --no-interaction

script: phpunit -c app
