language: php

php:
  - 5.5
  - 5.4

before_install:
    - sudo apt-get update

install:
    - sudo apt-get upgrade

before_script:
    - composer self-update
    - composer install

script: phpunit -c app
