language: php

php:
  - 5.5
  - 5.4

before_install:
    - composer self-update
    - cp app/config/parameters.yml.dist app/config/parameters.yml

before_script:
    - composer install

script: phpunit -c app
