services:
    forex.admin.user:
        class: Forex\Bundle\AdminBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Main, label: "Users" }
        arguments:
            - ~
            - Forex\Bundle\CoreBundle\Entity\User
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [ForexAdminBundle]]
            - [ setUserManager, [@fos_user.user_manager]]

    forex.admin.broker:
        class: Forex\Bundle\AdminBundle\Admin\BrokerAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Main, label: "Brokers" }
        arguments:
            - ~
            - Forex\Bundle\CoreBundle\Entity\Broker
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [ForexAdminBundle]]

    forex.admin.account:
        class: Forex\Bundle\AdminBundle\Admin\AccountAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Main, label: "Accounts" }
        arguments:
            - ~
            - Forex\Bundle\CoreBundle\Entity\Account
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [ForexAdminBundle]]

    forex.admin.payment:
        class: Forex\Bundle\AdminBundle\Admin\PaymentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Financial, label: "Payments" }
        arguments:
            - ~
            - Forex\Bundle\CoreBundle\Entity\Payment
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [ForexAdminBundle]]
