services:
    forex.admin.user:
        class: Forex\Bundle\AdminBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Main, label: "Users" }
        arguments:
            - ~
            - Forex\Bundle\CoreBundle\Entity\User
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [ForexAdminBundle]]
            - [ setUserManager, [@fos_user.user_manager]]

    forex.admin.broker:
        class: Forex\Bundle\AdminBundle\Admin\BrokerAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Main, label: "Brokers" }
        arguments:
            - ~
            - Forex\Bundle\CoreBundle\Entity\Broker
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [ForexAdminBundle]]
            - [ setEntityManager, [@doctrine.orm.default_entity_manager]]

    forex.admin.brokeraccounttype:
        class: Forex\Bundle\AdminBundle\Admin\BrokerAccountTypeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Main, label: "Broker Account Types" }
        arguments:
            - ~
            - Forex\Bundle\CoreBundle\Entity\BrokerAccountType
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [ForexAdminBundle]]

    forex.admin.account:
        class: Forex\Bundle\AdminBundle\Admin\AccountAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Main, label: "Accounts" }
        arguments:
            - ~
            - Forex\Bundle\CoreBundle\Entity\Account
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [ForexAdminBundle]]
            - [ setAccountManager, [@forex.account_manager]]

    forex.admin.execution_types:
        class: Forex\Bundle\AdminBundle\Admin\ExecutionTypeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Main, label: "Execution Types" }
        arguments:
            - ~
            - Forex\Bundle\CoreBundle\Entity\ExecutionType
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [ForexAdminBundle]]

    forex.admin.payment:
        class: Forex\Bundle\AdminBundle\Admin\PaymentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Financial, label: "Payments" }
        arguments:
            - ~
            - Forex\Bundle\CoreBundle\Entity\Payment
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [ForexAdminBundle]]
            - [ setPaymentManager, [@forex.payment_manager]]

    forex.admin.payout:
        class: Forex\Bundle\AdminBundle\Admin\PayoutAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Financial, label: "Payouts" }
        arguments:
            - ~
            - Forex\Bundle\CoreBundle\Entity\Payout
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [ForexAdminBundle]]

    forex.admin.partialpayout:
        class: Forex\Bundle\AdminBundle\Admin\PartialPayoutAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Financial, label: "Partial Payouts" }
        arguments:
            - ~
            - Forex\Bundle\CoreBundle\Entity\PartialPayout
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [ForexAdminBundle]]

    forex.admin.promotion:
        class: Forex\Bundle\AdminBundle\Admin\PromotionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Marketing, label: "Promotions" }
        arguments:
            - ~
            - Forex\Bundle\CoreBundle\Entity\Promotion
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [ForexAdminBundle]]

    forex.admin.regulator:
        class: Forex\Bundle\AdminBundle\Admin\RegulatorAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Regulations, label: "Regulators" }
        arguments:
            - ~
            - Forex\Bundle\CoreBundle\Entity\Regulator
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [ForexAdminBundle]]

    forex.admin.regulation:
        class: Forex\Bundle\AdminBundle\Admin\RegulationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Regulations, label: "Regulations" }
        arguments:
            - ~
            - Forex\Bundle\CoreBundle\Entity\Regulation
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [ForexAdminBundle]]

    forex.admin.currency:
        class: Forex\Bundle\AdminBundle\Admin\CurrencyAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Financial, label: "Currency" }
        arguments:
            - ~
            - Forex\Bundle\CoreBundle\Entity\Currency
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [ForexAdminBundle]]

    forex.admin.deposit_method:
        class: Forex\Bundle\AdminBundle\Admin\DepositMethodAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Financial, label: "Deposit Methods" }
        arguments:
            - ~
            - Forex\Bundle\CoreBundle\Entity\DepositMethod
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [ForexAdminBundle]]

    forex.admin.broker_suggestion:
        class: Forex\Bundle\AdminBundle\Admin\BrokerSuggestionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Feedback, label: "Broker Suggestions" }
        arguments:
            - ~
            - Forex\Bundle\CoreBundle\Entity\BrokerSuggestion
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [ForexAdminBundle]]

    forex.admin.complaint:
        class: Forex\Bundle\AdminBundle\Admin\ComplaintAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Feedback, label: "Complaints" }
        arguments:
            - ~
            - Forex\Bundle\CoreBundle\Entity\Complaint
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [ForexAdminBundle]]

    forex.admin.email.message:
        class: Forex\Bundle\AdminBundle\Admin\EmailMessageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Email, label: "Emails" }
        arguments:
            - ~
            - Forex\Bundle\EmailBundle\Entity\EmailMessage
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [ForexAdminBundle]]

    forex.admin.email.link:
        class: Forex\Bundle\AdminBundle\Admin\EmailLinkAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Email, label: "Links" }
        arguments:
            - ~
            - Forex\Bundle\EmailBundle\Entity\EmailLink
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [ForexAdminBundle]]

    forex.admin.email.open:
        class: Forex\Bundle\AdminBundle\Admin\EmailOpenAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Email, label: "Opens" }
        arguments:
            - ~
            - Forex\Bundle\EmailBundle\Entity\EmailOpen
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [ForexAdminBundle]]
