parameters:
    database_driver:   pdo_pgsql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     forex
    database_user:     forex
    database_password: forex

    mailer_transport:  smtp
    mailer_host:       "smtp.zoho.com"
    mailer_user:       "jsuggs@forexcashback.com"
    mailer_password:   "Admin3469"

    locale:            en
    secret:            S7uK4zene3ePHutHexeqeste
