parameters:
    database_driver:   pdo_pgsql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     forex
    database_user:     forex
    database_password: forex

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            S7uK4zene3ePHutHexeqeste
